import type { NextPage } from 'next';

import Head from 'next/head';
import Image from 'next/image';

import { GetServerSidePropsContext } from 'next';

import styles from '../styles/Home.module.css'

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
    console.log('Hello from getServerSideProps - node');

    return {
        props: {
            ctx_req_url: ctx.req.url,
            ctx_resolved_url: ctx.resolvedUrl.toString(),
            // @ts-ignore
            ctx_req_query: ctx.req.query || null,
            ctx_query: ctx.query,
            header: ctx.req.headers['my-header'] || null,
            cookie: ctx.req.cookies['my-cookie'] || null,
        }
    };
}

// @ts-ignore
const GsspNode: NextPage = (props, context) => {
    return (
        <div className={styles.container}>
            <Head>
                <title>gssp - node</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    This page uses getServerSideProps
                </h1>

                <div className={styles.grid}>
                    <pre>
                        {JSON.stringify(props, null, 4)}
                    </pre>
                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
                </a>
            </footer>
        </div>
    )
}

export default GsspNode;
